### PR TITLE
Create EVO_E_LeeaniTest_Jeth.xml

### PR DESCRIPTION
**Pull request by jetharius**
Heres the first file, please make any formatting changes and the like before I start moving on.

### CODE REVIEW

**Comment by Xahkarias** [comment]
Looks good so far, I can see that you are utilizing the "ModCheck.isModLoaded" method from ModCheck. Just to confirm, this means that integrating the ModCheck dll would be required correct? (Don't have a problem with that, just confirming my knowledge)

**Comment by jetharius** [comment]
I dont think so, I was of the impression that modcheck was a 1.0 integration to do a simple bool test for if a mod is loaded to avoid doing longer checks for if a mod exists or not.  (it loaded just fine into your current mod without the modcheck.dll and pushed the bodypart items into the leeani race without throwing any errors)

How do you want me to integrate the rest of the race mods, drop them into the same file or into singular ones?

**Comment by Xahkarias** [comment]
Oh interesting, I didn't realize it was a vanilla integration. I'm thinking of integrating ModCheck anyway to add those nice boolean xpath functions.

As for the patches, I am leaning to having seperate files. While as you said it would be easier to have a single file and use a replace feature for an ide, I think it would just be neater to have several patches, plus a bunch of ides (well at least VS code and iirc notepad++) have a replace all in a set of files. Your thoughts?

**Comment by jetharius** [comment]
True but remember to include a solution file for it for clones so that
other users can do pulls.  I also have a handful of integrations I would
like to help add assuming you agree.  One of the foremost is questionable
ethics, replacing the bench with vatgrown parts.  Do you have a discord, or
just accept my request on steam and we can directly chat.

**Comment by jetharius** [comment]
As soon as you accept the pull, ill start duplicating for all the other race files for the body parts.  I havent looked at the meat parts, I honestly feel that could be better relocated to a protein mash like questionable ethics. It would also be much easier to integrate by just including more recipes for the XXXmeat to protein mash.  I'd like to discuss further, accept my steam request or discord me at Jeth#7130

**Comment by Xahkarias** [comment]
Ah so for questionable ethics, you are proposing merging the organ growing process with their's? Seems interesting. And by meat parts, you are referring to the evolved meat created by butchering human meat correct? I am planning on removing the restriction on human meat to include any humanoid race installed as well.

**Pull request merged**
